export const cuisineList = [
    "American",
    "Asian",
    "Bakery",
    "Barbecue",
    "Burgers",
    "Cafe",
    "Chinese",
    "Desserts",
    "Fast Food",
    "Indian",
    "Italian",
    "Japanese",
    "Mediterranean",
    "Mexican",
    "Pizza",
    "Seafood",
    "Sushi",
    "Thai",
    "Vegetarian",
    "Vietnamese",
];